ENT-3671 Keep email field populated while switching in between new and old templates
edx/frontend-app-admin-portal pull request #388
Opened 2020-12-02 11:14 UTC by zamanafzal

Here is the [Jira Ticket](https://openedx.atlassian.net/browse/ENT-3671) for this issue.

2020-12-02 13:14 UTC, moconnell1453 approved these changes

2020-12-04 11:42 UTC, irfanuddinahmad approved these changes

2020-12-07 07:26 UTC, sameenfatima78 requested changes
Changes look good but shouldn't we add the same changes on Remind and Revoke modals too?

2020-12-08 10:07 UTC, zamanafzal commented
@sameenfatima78 For remind and revoke email field is not editable. So, we need this change for only assign modals.

2020-12-08 12:15 UTC, sameenfatima78 approved these changes

2020-12-08 12:16 UTC, merged